// Static portfolio case studies (temporary data layer)
// Rich content kept here (will migrate to CMS/DB/MDX later)

import type { Project } from '@/types/portfolio';

const now = new Date().toISOString();

export const portfolio: Project[] = [
  {
    slug: 'personal-portfolio-open-source',
    title: 'Personal Portfolio Platform',
    tagline: 'Open-source, SEO-first developer portfolio system',
    intro: 'A configurable open-source Next.js portfolio template enabling structured project, blog, and case study publishing with strong SEO foundations.',
    summary: 'Designed as a reusable system rather than a one-off site: modular data loaders, typed configuration, future MDX integration, and infrastructure readiness for both serverless (Vercel) and containerized (Docker) deployments.',
    company: 'Personal / Community',
    website: 'https://ammarhany.com',
    repository: 'https://github.com/amarhany20/TS-NextJS-PersonalPortfolio-v1-2025',
    visibility: 'public',
    access: 'open-source',
    status: 'in-progress',
    start: '2025-01',
    role: 'Full-stack Engineer & Architect',
    stack: ['Next.js App Router', 'TypeScript', 'Tailwind CSS', 'Resend', 'Docker', 'Structured Data'],
    features: [
      'SEO-first architecture',
      'Structured data & meta system',
      'Static-first with future dynamic path',
      'Reusable modular UI components',
      'Email pipeline via Resend',
      'Dual deploy: Vercel & Docker'
    ],
    sections: [
      {
        id: 'overview',
        title: 'Overview',
        body: 'Created a portable portfolio system focused on clarity, performance, and future extensibility. The core differentiator is the separation between domain data and presentation logic, enabling easy evolution toward a CMS-backed or MDX-powered content engine without rewriting components.',
        order: 1,
      },
      {
        id: 'architecture',
        title: 'Architecture & Patterns',
        body: 'Applied clean module boundaries: data loaders centralize structured constants; types define a stable contract; UI layers stay presentation-only. Planned support for MDX pipelines and incremental static regeneration. Environment variables are typed, and the system encourages config-driven customization.',
        order: 2,
      },
      {
        id: 'outcomes',
        title: 'Outcomes & Future',
        body: 'The platform is already usable as a template. Next milestones: MDX content ingestion, project taxonomies, RSS feed, and optional analytics integration. Long-term: plug-in style extension layer for custom blocks and AI-assisted content summaries.',
        order: 3,
      },
    ],
    gallery: [
      { id: 'personal-portfolio-1', image: '/images/portfolio/personal/cover.png', title: 'Landing Hero', alt: 'Primary hero section with dynamic highlights.' },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: 'spamguard-email-filtering-ml',
    title: 'SpamGuard – ML Email Spam Filter',
    tagline: 'Hybrid classical + transformer email classification',
    intro: 'An extensible machine learning pipeline combining scikit-learn feature models with a PyTorch BERT-based classifier to flag spam with high precision.',
    summary: 'Implements data ingestion, preprocessing (tokenization, lemmatization, vectorization), ensemble experimentation (Naive Bayes, SVM, Logistic Regression) and a transformer finetune path. Achieved 83% accuracy baseline with roadmap toward larger curated Kaggle corpora, whitelist/blacklist policy layer, and API exposure.',
    repository: 'https://github.com/amarhany20/python-spamguard',
    visibility: 'public',
    access: 'open-source',
    status: 'in-progress',
    start: '2024-12',
    role: 'ML Engineer',
    stack: ['Python', 'scikit-learn', 'PyTorch', 'BERT', 'Pandas'],
    features: [
      'Classical + transformer hybrid',
      'Preprocessing & vectorization pipeline',
      'Model comparison harness',
      'Planned REST API export',
      'Whitelist / blacklist roadmap'
    ],
    sections: [
      { id: 'pipeline', title: 'Pipeline', body: 'Cleans raw email text, normalizes casing, removes stop words, vectorizes using TF-IDF and transformer embeddings, enabling comparative evaluation across models.', order: 1 },
      { id: 'roadmap', title: 'Roadmap', body: 'Add dataset expansion, threshold tuning, policy layer (whitelist/blacklist rules), and containerized inference API.', order: 2 }
    ],
    gallery: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: 'farm-api-flask-cloud-run',
    title: 'Farm API – Livestock Data Platform',
    tagline: 'Secure REST API for livestock telemetry & scoring',
    intro: 'Cloud Run deployed Flask API integrating Firestore and Google Cloud Storage for structured livestock and vision dataset management.',
    summary: 'Implements modular endpoints, token + basic auth, CI/CD via Docker + GitHub Actions, and scalable storage patterns for media & metadata. Designed for reliability and easy extension into ML inference endpoints.',
    visibility: 'internal',
    access: 'proprietary',
    status: 'in-progress',
    start: '2024-11',
    role: 'Backend Engineer',
    stack: ['Python', 'Flask', 'Firestore', 'Google Storage', 'Docker', 'Cloud Run'],
    features: [
      'REST resource modularization',
      'Token & basic authentication',
      'CI/CD with GitHub Actions',
      'Media + metadata separation',
      'Scalable cloud deployment'
    ],
    confidentialNotes: 'Internal schema and endpoint authorization matrix under NDA.',
    sections: [
      { id: 'architecture', title: 'Architecture', body: 'Layered blueprint: routing → service layer → data access (Firestore / Storage) enabling isolated unit testing.', order: 1 },
      { id: 'deployment', title: 'Deployment', body: 'Containerized with minimal cold start impact, environment driven config, and secrets stored securely.', order: 2 }
    ],
    gallery: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: 'estrus-id-scoring-api',
    title: 'Estrus ID Scoring API',
    tagline: 'YOLOv8 powered estrus detection scoring service',
    intro: 'REST API applying multi-model analysis over livestock video frames to compute estrus probability & tracking metrics.',
    summary: 'Integrates Ultralytics YOLOv8 detection outputs into a composite scoring algorithm, exposing structured JSON responses for downstream automation. Includes model evaluation workflow and reproducible environment.',
    visibility: 'internal',
    access: 'proprietary',
    status: 'in-progress',
    start: '2024-11',
    role: 'Computer Vision Engineer',
    stack: ['Python', 'YOLOv8', 'REST API', 'Pandas'],
    features: [
      'Multi-model scoring',
      'Detection feature extraction',
      'Structured JSON outputs',
      'Evaluation workflow scripts'
    ],
    confidentialNotes: 'Scoring weighting heuristics and threshold logic confidential.',
    sections: [
      { id: 'scoring', title: 'Scoring System', body: 'Aggregates detection confidence, temporal consistency, and positional features into normalized estrus score.', order: 1 }
    ],
    gallery: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: 'estrus-jetson-realtime-pipeline',
    title: 'Estrus Jetson Real-time Pipeline',
    tagline: 'Edge-optimized estrus detection on NVIDIA Jetson',
    intro: 'Hardware accelerated inference pipeline consuming multiple RTSP streams and executing batched YOLOv8 detection.',
    summary: 'Implements multithreaded frame capture, GPU utilization tuning, and resilient reconnection logic. Provides structured event hooks for alert generation and data offloading to cloud storage.',
    visibility: 'internal',
    access: 'proprietary',
    status: 'in-progress',
    start: '2025-01',
    role: 'Edge AI Engineer',
    stack: ['Python', 'YOLOv8', 'NVIDIA Jetson', 'RTSP', 'Multithreading'],
    features: [
      'Parallel stream ingestion',
      'GPU accelerated inference',
      'Auto reconnection strategy',
      'Event hook architecture'
    ],
    confidentialNotes: 'Edge optimization metrics and alert trigger thresholds private.',
    sections: [
      { id: 'throughput', title: 'Performance', body: 'Balanced batch size, frame skip strategies, and memory reuse to preserve low latency under load.', order: 1 }
    ],
    gallery: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: 'iot-gate-rfid-pipeline',
    title: 'IoT Gate RFID Pipeline',
    tagline: 'Multithreaded livestock identification gateway',
    intro: 'RFID-enabled identification and video capture system coordinating USB / RTSP camera feeds with ID tagging.',
    summary: 'Implements robust multithreading, camera abstraction, and data handoff to storage for downstream ML labeling. Ensures cross-platform operability (Linux/Windows) and extensibility toward sensor fusion.',
    visibility: 'internal',
    access: 'proprietary',
    status: 'in-progress',
    start: '2025-01',
    role: 'Software Engineer',
    stack: ['Python', 'Multithreading', 'RTSP', 'RFID', 'Google Storage'],
    features: [
      'Thread-safe capture loops',
      'RFID tag association',
      'Cross-platform support',
      'Data pipeline backbone'
    ],
    confidentialNotes: 'Specific device integration adapters and buffering strategies confidential.',
    sections: [
      { id: 'concurrency', title: 'Concurrency Design', body: 'Queue-based producer/consumer architecture isolates camera IO from processing to prevent frame drops.', order: 1 }
    ],
    gallery: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: 'data-checker-video-filtering',
    title: 'Data Checker – Video Frame Filtering',
    tagline: 'Automated frame extraction & tagging utility',
    intro: 'Pipeline tool for extracting, filtering, and labeling frames to streamline dataset curation.',
    summary: 'Automates frame sampling heuristics (interval, motion cues) and applies ID tagging schema to reduce manual dataset preparation effort for CV training.',
    visibility: 'internal',
    access: 'proprietary',
    status: 'in-progress',
    start: '2025-01',
    role: 'Data Engineering Developer',
    stack: ['Python', 'OpenCV', 'Automation'],
    features: [
      'Heuristic frame selection',
      'Automated ID tagging',
      'Dataset preparation speedup'
    ],
    sections: [
      { id: 'heuristics', title: 'Heuristics', body: 'Supports pluggable frame selection strategies (fixed rate, scene change, motion threshold).', order: 1 }
    ],
    gallery: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: 'cv-training-suite-yolov8',
    title: 'Computer Vision Training Suite',
    tagline: 'Modular YOLOv8 training & evaluation toolkit',
    intro: 'Toolkit wrapping dataset prep, augmentation, training configuration, and performance benchmarking for iterative CV model development.',
    summary: 'Provides scripts & modules for YAML generation, augmentation recipes, batch experimentation, and metrics comparison to accelerate model refinement cycles.',
    visibility: 'public',
    access: 'open-source',
    status: 'in-progress',
    start: '2024-12',
    role: 'Computer Vision Engineer',
    stack: ['Python', 'YOLOv8', 'OpenCV', 'Automation'],
    features: [
      'Dataset preparation tools',
      'Augmentation workflows',
      'Batch experiment scripts',
      'Benchmark metrics export'
    ],
    sections: [
      { id: 'automation', title: 'Automation', body: 'Automated generation of dataset structure & config eliminates repetitive manual steps between experiments.', order: 1 }
    ],
    gallery: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: 'ai-analysis-validation-app',
    title: 'AI Analysis Validation Application',
    tagline: 'GUI tool for multi-model ID accuracy review',
    intro: 'Desktop validation utility enabling analysts to compare predicted IDs, inspect confusion cases, and export structured Excel summaries.',
    summary: 'Integrates database retrieval, result caching, and interactive filtering to streamline human-in-the-loop evaluation for model iteration.',
    visibility: 'internal',
    access: 'proprietary',
    status: 'in-progress',
    start: '2025-02',
    role: 'Python Developer',
    stack: ['Python', 'GUI Toolkit', 'Excel Export'],
    features: [
      'Interactive comparison UI',
      'Excel export automation',
      'Caching for large datasets'
    ],
    sections: [
      { id: 'workflow', title: 'Workflow', body: 'Designed to tighten feedback loop between training runs and qualitative analyst review.', order: 1 }
    ],
    gallery: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: 'live-object-counter-jetson',
    title: 'Live Object Counter (Internship)',
    tagline: 'Real-time detection & counting on edge devices',
    intro: 'Computer vision application counting & annotating objects in real-time optimized for Jetson deployment.',
    summary: 'Utilizes Ultralytics + Supervision + OpenCV stack, optimizing preprocessing and inference loops for edge throughput and stability.',
    repository: null,
    visibility: 'internal',
    access: 'proprietary',
    status: 'archived',
    start: '2024-06',
    end: '2024-08',
    role: 'Computer Vision Intern',
    stack: ['Python', 'YOLOv8', 'OpenCV', 'Jetson'],
    features: [
      'Edge performance tuning',
      'Real-time counting',
      'Stability optimizations'
    ],
    sections: [
      { id: 'optimizations', title: 'Optimizations', body: 'Reduced latency through preallocated buffers and selective frame decoding strategies.', order: 1 }
    ],
    gallery: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: 'forums-web-application-aspnet',
    title: 'Forums Web Application (ASP.NET)',
    tagline: 'Role-based discussion & content platform',
    intro: 'ASP.NET MVC forum enabling authenticated users to create posts, comment, and engage in structured threads.',
    summary: 'Implements Entity Framework models, authentication/authorization, and clean separation of controllers, services, and data models with scalable DB schema.',
    repository: 'https://github.com/amarhany20/Toros-University-ASP.NET-MVC-FORUMS-APP',
    visibility: 'public',
    access: 'open-source',
    status: 'archived',
    start: '2023-10',
    end: '2024-01',
    role: 'Full-stack .NET Developer',
    stack: ['C#', 'ASP.NET MVC', 'Entity Framework', 'MSSQL'],
    features: [
      'Auth & role gating',
      'Threaded discussions',
      'Entity Framework data layer'
    ],
    sections: [
      { id: 'security', title: 'Security', body: 'Implemented proper password handling and role-based action filtering in controllers.', order: 1 }
    ],
    gallery: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: 'facialid-recognition-app',
    title: 'FacialID – Face Recognition App',
    tagline: 'Multi-algorithm face identification desktop tool',
    intro: 'Tkinter-based GUI face recognition app leveraging multiple ML libraries for detection and identification.',
    summary: 'Employs OpenCV for detection, PyTorch/TensorFlow models for embeddings/classification, and scikit-learn pipelines for experimentation. Automates face cropping & dataset management.',
    repository: 'https://github.com/amarhany20/FacialID',
    visibility: 'public',
    access: 'open-source',
    status: 'archived',
    start: '2023-07',
    end: '2023-11',
    role: 'Python Developer',
    stack: ['Python', 'Tkinter', 'PyTorch', 'TensorFlow', 'scikit-learn', 'OpenCV'],
    features: [
      'GUI face recognition',
      'Multi-framework models',
      'Automated dataset prep'
    ],
    sections: [
      { id: 'multi-model', title: 'Multi-Model', body: 'Abstracted interface enables swapping embedding or classification strategies for comparison.', order: 1 }
    ],
    gallery: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: 'teknofest-autonomous-harvesting-cv',
    title: 'Teknofest 2023 CV Backend',
    tagline: 'Autonomous harvesting vision prototype',
    intro: 'Computer vision backend for autonomous fruit/vegetable detection in competition setting (Teknofest).',
    summary: 'YOLOv8 based detection with cropping & color analysis pipeline, Flask interface for demonstration and evaluation. Achieved competition ranking (25th) among broad field.',
    repository: 'https://github.com/amarhany20/Teknofest-Autonomous-Harvesting-Robot-Computer-Vision-Backend',
    visibility: 'public',
    access: 'open-source',
    status: 'archived',
    start: '2023-03',
    end: '2023-05',
    role: 'Computer Vision Engineer',
    stack: ['Python', 'YOLOv8', 'Flask', 'OpenCV'],
    features: [
      'Object detection',
      'Auto cropping',
      'Color classification'
    ],
    sections: [
      { id: 'competition', title: 'Competition', body: 'Engineered time-efficient model iteration to meet contest constraints & deliver stable demo.', order: 1 }
    ],
    gallery: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: 'self-driving-car-behavioral-cloning',
    title: 'Self-Driving Car (Behavioral Cloning)',
    tagline: 'CNN-based end-to-end driving model',
    intro: 'Deep learning project training a CNN to mimic human driving behavior using recorded steering + camera data.',
    summary: 'Collected driving dataset, performed augmentation, trained Keras CNN architecture to achieve stable autonomous laps without collisions.',
    repository: 'https://github.com/amarhany20/Private-Self-Driving-Car',
    visibility: 'public',
    access: 'open-source',
    status: 'archived',
    start: '2023-02',
    end: '2023-06',
    role: 'ML Engineer',
    stack: ['Python', 'TensorFlow Keras', 'Data Augmentation'],
    features: [
      'Behavioral cloning',
      'Data augmentation',
      'CNN training pipeline'
    ],
    sections: [
      { id: 'training', title: 'Training', body: 'Balanced dataset with recovery driving samples to prevent drift off center line.', order: 1 }
    ],
    gallery: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: 'engineering-firm-laravel-platform',
    title: 'Engineering Firm Website (Laravel)',
    tagline: 'Role-based project showcase & admin',
    intro: 'Laravel-based platform with admin management of projects, users, and dynamic SEO meta generation.',
    summary: 'Implements role-based access, CRUD management, and optimized meta tags for improved search visibility while maintaining clean Blade templating.',
    repository: 'https://github.com/amarhany20/laravel-CompanyWebsiteVersion2',
    visibility: 'public',
    access: 'open-source',
    status: 'archived',
    start: '2023-09',
    end: '2023-12',
    role: 'Full-stack Laravel Developer',
    stack: ['Laravel 9', 'PHP', 'MySQL', 'Bootstrap'],
    features: [
      'Admin project management',
      'Role-based access',
      'Dynamic SEO meta'
    ],
    sections: [
      { id: 'admin', title: 'Admin Panel', body: 'Centralized CRUD for content & permissions with validation middleware.', order: 1 }
    ],
    gallery: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: 'real-estate-multilingual-wix',
    title: 'Real Estate Site (Wix Velo)',
    tagline: 'Lead-focused multilingual property showcase',
    intro: 'Multilingual property marketing site built with Wix Velo and custom JavaScript enhancements for lead capture.',
    summary: 'Implements CMS-backed property entries, email lead routing, and SEO-friendly structured content patterns.',
    visibility: 'public',
    access: 'client-owned',
    status: 'live',
    start: '2024-05',
    end: '2024-06',
    role: 'Web Developer',
    stack: ['JavaScript', 'Wix Velo', 'CMS'],
    features: [
      'Lead capture flows',
      'Multilingual content',
      'SEO structured layout'
    ],
    sections: [
      { id: 'leads', title: 'Lead Strategy', body: 'Optimized forms + routing to maximize conversion and follow-up speed.', order: 1 }
    ],
    gallery: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: 'istone-company-management-wpf',
    title: 'IStone Company Management (WPF)',
    tagline: 'Desktop operations & role-based tracking',
    intro: 'WPF desktop system managing customers, work status, inventory, and payments with roles & authorization.',
    summary: 'Implements real-time status updates, multi-role capability gating, and modular service classes for maintainability.',
    repository: 'https://github.com/amarhany20/IStone-Company-Management',
    visibility: 'public',
    access: 'open-source',
    status: 'archived',
    start: '2023-04',
    end: '2023-08',
    role: 'C# Developer',
    stack: ['C#', 'WPF', 'MSSQL'],
    features: [
      'Role-based operations',
      'Inventory tracking',
      'Payment management'
    ],
    sections: [
      { id: 'roles', title: 'Roles', body: 'Employees, managers, owners each scoped to relevant modules & actions.', order: 1 }
    ],
    gallery: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: 'inventory-system-wpf',
    title: 'Inventory System (WPF)',
    tagline: 'Multi-user desktop inventory management',
    intro: 'WPF inventory platform with user-based login and full CRUD + history tracking.',
    summary: 'Supports concurrent users via server deployment, detailed change logs, and protected data operations for reliability.',
    repository: 'https://github.com/amarhany20/Personal-CSharp-WPF-InventorySystem',
    visibility: 'public',
    access: 'open-source',
    status: 'archived',
    start: '2023-02',
    end: '2023-06',
    role: 'C# Developer',
    stack: ['C#', 'WPF', 'SQLite'],
    features: [
      'User-based login',
      'Inventory history logs',
      'Server-ready deployment'
    ],
    sections: [
      { id: 'logging', title: 'Logging', body: 'Tracks item adds, removes, edits with timestamp & user attribution.', order: 1 }
    ],
    gallery: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: 'web-crawler-multithreaded-wpf',
    title: 'Robust Multithreaded Web Crawler',
    tagline: 'Recursive domain-scoped URL extraction',
    intro: 'WPF crawler traversing domain pages concurrently to extract and list anchor links.',
    summary: 'Multithreading ensures UI responsiveness; filtration prevents external domain drift while providing full crawl coverage.',
    repository: 'https://github.com/amarhany20/Toros-University-WebCrawler-CSHARP-WPF-MSSQL',
    visibility: 'public',
    access: 'open-source',
    status: 'archived',
    start: '2023-01',
    end: '2023-04',
    role: 'C# Developer',
    stack: ['C#', 'WPF', 'MSSQL'],
    features: [
      'Concurrent crawling',
      'Domain filtration',
      'Anchor extraction'
    ],
    sections: [
      { id: 'concurrency', title: 'Concurrency', body: 'Thread pool prevents UI blocking and balances crawl throughput.', order: 1 }
    ],
    gallery: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: 'windows-notes-app-wpf',
    title: 'Windows Notes App (WPF)',
    tagline: 'User-isolated note taking system',
    intro: 'WPF application for creating, searching, editing, and deleting personal notes with per-user isolation.',
    summary: 'Implements responsive search, validation-heavy inputs, and multithreaded operations to maintain UI responsiveness.',
    repository: 'https://github.com/amarhany20/csharp_wpf_notesapp',
    visibility: 'public',
    access: 'open-source',
    status: 'archived',
    start: '2022-12',
    end: '2023-03',
    role: 'C# Developer',
    stack: ['C#', 'WPF', 'SQL'],
    features: [
      'Real-time search',
      'Validation rules',
      'Background threading'
    ],
    sections: [
      { id: 'ux', title: 'UX', body: 'Prioritized immediate feedback and non-blocking operations for smooth editing experience.', order: 1 }
    ],
    gallery: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: 'school-library-system-wpf',
    title: 'School Library System (WPF)',
    tagline: 'Role-gated library & lending management',
    intro: 'Comprehensive library tracking system with inventory, lending timelines, and role-based operations.',
    summary: 'Supports Students, Lecturers, Admin roles with time tracking for rentals, notifications, and stock control workflows.',
    repository: 'https://github.com/amarhany20/Toros-University-Library-System-CSHARP-WPF-MSSQL',
    visibility: 'public',
    access: 'open-source',
    status: 'archived',
    start: '2022-11',
    end: '2023-02',
    role: 'C# Developer',
    stack: ['C#', 'WPF', 'MSSQL'],
    features: [
      'Role-based actions',
      'Rental time tracking',
      'Notification system'
    ],
    sections: [
      { id: 'roles', title: 'Roles', body: 'Authorization gates ensure each role operates only on permitted modules.', order: 1 }
    ],
    gallery: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: 'school-management-system-java',
    title: 'School Management System (Java)',
    tagline: 'Academic scheduling & course management',
    intro: 'Java + SQLite system managing courses, exams, schedules, and announcements with role distinctions.',
    summary: 'Enables lecturer-led grade management, announcements, and consolidated schedule organization improving academic workflow clarity.',
    repository: 'https://github.com/amarhany20/TOROS-UNIVERSITY-PROJECTS/tree/main/Java%20School%20Management%20Project/AmmarHanyEzeldinAbdelrazik195050902Java/SchoolManagementSystem',
    visibility: 'public',
    access: 'open-source',
    status: 'archived',
    start: '2022-10',
    end: '2023-01',
    role: 'Java Developer',
    stack: ['Java', 'SQLite'],
    features: [
      'Exam scheduling',
      'Announcements',
      'Grade management'
    ],
    sections: [
      { id: 'scheduling', title: 'Scheduling', body: 'Consolidated timetable + exam planning reduces conflicts and manual coordination.', order: 1 }
    ],
    gallery: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: 'cashier-system-wpf',
    title: 'Cashier System (WPF)',
    tagline: 'Inventory-aware point of sale',
    intro: 'Point of sale system with order history, inventory synchronization, and role-gated operations.',
    summary: 'Auto-tracks stock levels, provides admin audit over order history, and supports multi-user deployment for retail environments.',
    repository: 'https://github.com/amarhany20/Toros-University-Cashier-System-CSHARP-WPF',
    visibility: 'public',
    access: 'open-source',
    status: 'archived',
    start: '2022-12',
    end: '2023-04',
    role: 'C# Developer',
    stack: ['C#', 'WPF', 'MSSQL'],
    features: [
      'Order history',
      'Auto stock tracking',
      'Multi-user ready'
    ],
    sections: [
      { id: 'stock', title: 'Stock Logic', body: 'Inventory adjustments bound to completed order transactions with rollback safeguards.', order: 1 }
    ],
    gallery: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: 'notes-and-tasks-android-app',
    title: 'Notes & Tasks Android App',
    tagline: 'Mobile notes and task management',
    intro: 'Android app enabling note and task creation, pinning, searching, and organization using RoomsDB (SQLite).',
    summary: 'Implements entity-based persistence, fast search, and intuitive task state transitions to support productivity workflows.',
    repository: null,
    visibility: 'public',
    access: 'open-source',
    status: 'archived',
    start: '2023-01',
    end: '2023-04',
    role: 'Android Developer',
    stack: ['Java', 'Android Studio', 'RoomsDB', 'SQLite'],
    features: [
      'Pinned notes',
      'Task state tracking',
      'Fast indexed search'
    ],
    sections: [
      { id: 'persistence', title: 'Persistence', body: 'Normalized entities and indices provide fast retrieval for note search UX.', order: 1 }
    ],
    gallery: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: 'formoreco-company-website',
    title: 'FormoreCo Marketing Website',
    tagline: 'Lightweight static corporate presence',
    intro: 'A fast static marketing site with a maintainable content structure and zero-maintenance deployment pipeline.',
    summary: 'Built for simplicity and reliability. Prioritized accessibility, performance budgets, and frictionless content iteration using structured sections and responsive, reusable components.',
    company: 'FormoreCo',
    website: 'https://formoreco.com',
    repository: null,
    visibility: 'public',
    access: 'client-owned',
    status: 'live',
    start: '2024-11',
    end: '2024-12',
    role: 'Frontend Engineer',
    stack: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Vercel'],
    features: [
      'Static export optimized',
      'SEO core essentials',
      'Reusable section components',
      'Accessible responsive layout'
    ],
    sections: [
      {
        id: 'overview',
        title: 'Overview',
        body: 'Implemented a structured marketing site focusing on clarity of messaging and maintainability. Content sections are data-driven to reduce future code churn.',
        order: 1,
      },
      {
        id: 'performance',
        title: 'Performance & SEO',
        body: 'Achieved strong Lighthouse scores through static generation, prefetching strategies, and careful asset discipline. Implemented Open Graph tags and sitemap.',
        order: 2,
      },
      {
        id: 'operations',
        title: 'Operations',
        body: 'Deployment via Vercel with minimal maintenance footprint. Content updates performed through simple data edits rather than component rewrites.',
        order: 3,
      },
    ],
    gallery: [
      { id: 'formoreco-1', image: '/images/portfolio/formoreco/home.png', title: 'Homepage', alt: 'Hero and services overview.' },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: 'homeco-pricing-system',
    title: 'The Home Co Pricing System',
    tagline: 'Centralized B2B pricing & estimation platform',
    intro: 'A production platform generating accurate, bilingual furniture pricing documents with role-based control and operational auditability.',
    summary: 'Automated complex pricing workflows, enforcing deterministic calculation rules while providing resilience features like archival, backup/restore, and preset export/import to ensure business continuity.',
    company: 'The Home Co',
    website: 'https://pricingsystem.thehomecoeg.com',
    repository: null,
    visibility: 'internal',
    access: 'proprietary',
    status: 'live',
    start: '2024-06',
    end: '2024-12',
    role: 'Full-stack Engineer',
    stack: ['Next.js', 'TypeScript', 'PostgreSQL', 'Prisma', 'Docker', 'Linux VPS'],
    features: [
      'Role-based access & auditing',
      'Deterministic pricing engine',
      'Bilingual PDF generation',
      'Resource presets & archival',
      'Operational backups & exports'
    ],
    confidentialNotes: 'Internal business logic details and calculation rules protected under confidentiality agreements.',
    sections: [
      { id: 'overview', title: 'Overview', body: 'Designed to replace fragmented spreadsheets with a unified controlled system, ensuring pricing consistency across teams.', order: 1 },
      { id: 'engine', title: 'Pricing Engine', body: 'Rule-driven engine applying cost, margin, and discount precedence with deterministic outputs.', order: 2 },
      { id: 'resilience', title: 'Resilience & Ops', body: 'Implemented archival, backup/restore, and import/export to mitigate data loss and enable safe iteration.', order: 3 },
    ],
    gallery: [
      { id: 'homeco-pricing-1', image: '/images/portfolio/homeco/pricing-dashboard.png', title: 'Dashboard', alt: 'Primary pricing workspace.' },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: 'homeco-headless-ecommerce',
    title: 'The Home Co Headless E-Commerce',
    tagline: 'Luxury furniture storefront powered by Shopify + Next.js',
    intro: 'A headless commerce frontend emphasizing premium brand presentation, performance, and scalable structured content.',
    summary: 'Bridged Shopify Storefront API with a custom Next.js experience, enabling curated collection pages, metaobject-powered content, and future multilingual expansion.',
    company: 'The Home Co',
    website: 'https://staging.thehomecoeg.com',
    repository: null,
    visibility: 'internal',
    access: 'client-owned',
    status: 'in-progress',
    start: '2025-02',
    role: 'IT Manager / Lead Engineer',
    stack: ['Next.js', 'TypeScript', 'Shopify Storefront API', 'GraphQL', 'Tailwind CSS'],
    features: [
      'Headless storefront architecture',
      'Shopify metaobjects CMS usage',
      'Custom collection merchandising',
      'GraphQL Storefront integration',
      'Multilingual foundations'
    ],
    confidentialNotes: 'Certain merchandising logic and internal tooling integrations are restricted under NDA.',
  sections: [
      { id: 'overview', title: 'Overview', body: 'Focused on premium aesthetic and performance while decoupling content management to Shopify for non-technical staff.', order: 1 },
      { id: 'integration', title: 'Integration Strategy', body: 'Used Shopify Storefront GraphQL API for products, collections, and marketing content backing a modern Next.js UI.', order: 2 },
      { id: 'scalability', title: 'Scalability & Roadmap', body: 'Prepared for future multilingual, personalization, and analytics-driven optimization.', order: 3 },
    ],
    gallery: [
      { id: 'homeco-headless-1', image: '/images/portfolio/homeco/headless-home.png', title: 'Staging Home', alt: 'Early staging hero concept.' },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: 'persona-x-saas-platform',
    title: 'Persona X – Dynamic Resume & Portfolio SaaS',
    tagline: 'Automated personal professional identity generator',
    intro: 'A multi-tenant SaaS platform generating dynamic resumes, portfolios, and profile sites from structured user career data.',
    summary: 'Persona X centralizes professional data (experience, education, skills, projects) and exposes it through dynamic rendering pipelines: export-ready CV layouts, themed portfolio sites, API access for AI agents, and future analytics overlays. Built with a clean modular backend + secure auth.',
    company: 'A Squared Tech',
    website: undefined,
    repository: undefined,
    visibility: 'internal',
    access: 'proprietary',
    status: 'in-progress',
    start: '2025-03',
    role: 'Co‑founder / Lead Engineer',
    stack: ['Next.js', 'FastAPI', 'PostgreSQL', 'Clerk Auth', 'REST API'],
    features: [
      'Subscription multi-tenant architecture',
      'Dynamic CV + portfolio generation',
      'Structured professional data store',
      'API + AI agent access layer',
      'Role-based user access',
      'Extensible theming system'
    ],
    confidentialNotes: 'Core generation engine and data normalization logic under active design; internal roadmap proprietary.',
    sections: [
      { id: 'vision', title: 'Vision', body: 'Provide a persistent professional “source of truth” so users never re-enter the same career data across CV builders or website templates. Everything renders on-demand.', order: 1 },
      { id: 'architecture', title: 'Architecture', body: 'Frontend in Next.js (app router) consuming a FastAPI service layer. Data modeled in PostgreSQL with modular resource domains (users, profiles, entries, render templates). Auth & org tenancy via Clerk.', order: 2 },
      { id: 'features', title: 'Feature Set', body: 'Planned modules: CV generator, portfolio theming engine, API tokens for programmatic access, insights layer (timeline, skill density), and export queue.', order: 3 }
    ],
    gallery: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: 'eggersmann-uae-luxury-kitchen',
    title: 'Eggersmann UAE – Luxury Kitchen Website',
    tagline: 'Premium multilingual luxury kitchen brand presence',
    intro: 'High-end multilingual brand site combining structured custom content types with refined UI for a luxury kitchen manufacturer.',
    summary: 'Implemented flexible content modeling with Pods (projects, materials, finishes) and Elementor Pro for controlled visual layouts. Added custom PHP enhancements for performance, interaction, and editorial efficiency while preserving brand identity.',
    company: 'Eggersmann UAE',
    website: 'https://eggersmann.ae',
    repository: undefined,
    visibility: 'public',
    access: 'client-owned',
    status: 'live',
    start: '2024-10',
    end: '2024-12',
    role: 'Lead Web Developer',
    stack: ['WordPress', 'Elementor Pro', 'Pods', 'Custom PHP', 'Cloudways'],
    features: [
      'Custom post type relationships',
      'Multilingual content structure',
      'Performance + caching strategy',
      'Luxury brand-responsive design',
      'Dynamic project & material linking'
    ],
    sections: [
      { id: 'overview', title: 'Overview', body: 'Delivered a premium responsive experience reflecting a physical luxury showroom feel, emphasizing visual consistency and interactive subtlety.', order: 1 },
      { id: 'content-model', title: 'Content Modeling', body: 'Used Pods to define Projects, Materials, Finishes, enabling editors to assemble rich showcases without developer changes.', order: 2 },
      { id: 'performance', title: 'Performance & Ops', body: 'Optimized caching (Varnish, object cache), asset discipline, and selective preloading for perceived-speed improvements.', order: 3 }
    ],
    gallery: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: 'kingfisher-logistics-shipment-tracking',
    title: 'Kingfisher Logistics – Shipment Tracking System',
    tagline: 'Role-based logistics tracking & document workflow',
    intro: 'Custom WordPress plugin powering secure multi-role shipment tracking with live status updates and document attachments.',
    summary: 'Replaced manual spreadsheet/email-based processes with a structured plugin: CRUD shipment lifecycle, attachments, auditability, and secure external visibility for guests. Designed for operational clarity and long-term maintainability.',
    company: 'Kingfisher Logistics',
    website: 'https://kfl-sy.com',
    repository: undefined,
    visibility: 'public',
    access: 'client-owned',
    status: 'live',
    start: '2024-08',
    end: '2024-10',
    role: 'Full-stack WordPress Engineer',
    stack: ['WordPress', 'PHP', 'Custom Plugin', 'Elementor'],
    features: [
      'Role-based shipment CRUD',
      'Attachment handling',
      'Status timeline history',
      'Secure guest tracking view',
      'Scalable plugin architecture'
    ],
    sections: [
      { id: 'overview', title: 'Overview', body: 'Implemented a structured plugin to centralize logistics updates and reduce coordination overhead.', order: 1 },
      { id: 'roles', title: 'Access Model', body: 'Managers, employees, and anonymous guests each receive scoped capabilities aligning with least-privilege principles.', order: 2 },
      { id: 'operations', title: 'Operations & Maintainability', body: 'Designed plugin internals with hooks-based extensibility and clear separation between data, rendering, and capability checks.', order: 3 }
    ],
    gallery: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: 'al-serif-company-multilingual-site',
    title: 'Al Serif Company – Multilingual Business Website',
    tagline: 'Rapid-delivered tri-language corporate presence',
    intro: 'One-page multilingual business site delivered under a 12-hour execution window with cohesive branding and responsive polish.',
    summary: 'Focused on speed of delivery without sacrificing structure: dark/light theming, three language variants, and performance-conscious asset use. Provided branded system (fonts, palette) and email setup for professional communications.',
    company: 'Al Serif Company',
    website: 'https://alserifcompany.com.tr',
    repository: undefined,
    visibility: 'public',
    access: 'client-owned',
    status: 'live',
    start: '2024-09',
    end: '2024-09',
    role: 'Web Engineer',
    stack: ['WordPress', 'Elementor', 'Custom CSS', 'WHM / cPanel'],
    features: [
      'Tri-language support',
      'Dark / light mode design',
      'Brand identity system',
      'High performance delivery',
      'Rapid 12-hour execution'
    ],
    sections: [
      { id: 'overview', title: 'Overview', body: 'Delivered essential corporate presence across English, Turkish, and Arabic with consistent design language.', order: 1 },
      { id: 'branding', title: 'Brand System', body: 'Established a small but scalable design identity: typography, palette, motion decisions, and contrast rules for accessibility.', order: 2 },
      { id: 'delivery', title: 'Execution Speed', body: 'Optimized build approach to meet aggressive turnaround while preserving extensibility for future sections.', order: 3 }
    ],
    gallery: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: 'kiwify-hani-wamari-orders-tracking-app',
    title: 'Kiwify Tech – Hani Wa Mari Orders Tracking App',
    tagline: 'Flutter mobile app for restaurant operational management',
    intro: 'A production Flutter app (Arabic-first) integrating with an ASP.NET backend to manage restaurant order lifecycles and roles.',
    summary: 'Implements dynamic page generation driven by backend descriptors, unified model + settings system, and modular architecture layers (core, services, widgets, dto, screens). Built for scalability, localization, and future multi-language expansion with strong DTO-based API integration.',
    company: 'Kiwify Tech',
    website: undefined,
    repository: null,
    domain: 'Mobile',
    visibility: 'internal',
    access: 'proprietary',
    status: 'in-progress',
    start: '2025-01',
    role: 'Flutter Engineer',
    stack: ['Flutter', 'Dart', 'REST API', 'Localization'],
    features: [
      'Dynamic server-driven pages',
      'Arabic-first localization',
      'Modular layered architecture',
      'DTO-based API integration',
      'Version & update management'
    ],
  confidentialNotes: 'Internal operational flow specifics and proprietary generation logic under NDA.',
  sections: [
      { id: 'architecture', title: 'Architecture', body: 'Separated UI widgets, services, models, DTOs, and configuration to allow backend-driven UI expansion without code duplication.', order: 1 },
      { id: 'localization', title: 'Localization', body: 'Implemented right-to-left friendly layouts and time zone utilities; groundwork laid for future multi-language switcher.', order: 2 }
    ],
    gallery: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: 'kiwify-hani-wamari-orders-backend',
    title: 'Kiwify Tech – Hani Wa Mari Backend',
    tagline: 'Stateless ASP.NET order tracking & role platform',
    intro: 'A secure ASP.NET + PostgreSQL backend powering multi-role restaurant order workflows with JWT auth and auditability.',
    summary: 'Implements RESTful architecture, Identity-based auth, repository/service layering, DTOs, and role-specific state transitions (locking, preparation, delivery). Designed statelessly for horizontal scalability and cost efficiency.',
    company: 'Kiwify Tech',
    website: undefined,
    repository: null,
    domain: 'Backend',
    visibility: 'internal',
    access: 'proprietary',
    status: 'in-progress',
    start: '2025-01',
    role: 'Backend Engineer (C#)',
    stack: ['ASP.NET Core', 'C#', 'PostgreSQL', 'JWT', 'Docker'],
    features: [
      'JWT authentication & roles',
      'Order lifecycle management',
      'Archiving & traceability',
      'Layered clean architecture',
      'Stateless scaling design'
    ],
  confidentialNotes: 'Role permission matrix, encryption details & operational metrics are confidential.',
  sections: [
      { id: 'modules', title: 'Modules', body: 'Controllers → Services → Repositories with DTO mappers enforce separation and testability.', order: 1 },
      { id: 'security', title: 'Security', body: 'JWT with role-based authorization and future plan for permission flags; sanitized inputs & consistent exception middleware.', order: 2 }
    ],
    gallery: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: 'domogreen-research-platform-backend-v2-drf',
    title: 'Domogreen Research Platform Backend V2',
    tagline: 'Modular DRF backend with collaboration systems',
    intro: 'A redesigned Django REST Framework backend with PostgreSQL and modular services powering research collaboration.',
    summary: 'Built messaging, chat, user management, and collaboration modules with JWT auth & role-based access. Employed modular app-per-domain organization, repository + service abstraction, and serializer-driven validation.',
    company: 'Domogreen',
    website: undefined,
    repository: null,
    domain: 'Backend',
    visibility: 'internal',
    access: 'proprietary',
    status: 'in-progress',
    start: '2025-02',
    role: 'Python Backend Engineer',
    stack: ['Django REST Framework', 'Python', 'PostgreSQL', 'JWT'],
    features: [
      'Messaging & chat system',
      'Role-based authorization',
      'Repository/service layering',
      'Serializer validation pipeline',
      'Scalable modular apps'
    ],
  confidentialNotes: 'Internal research data models & AI integration endpoints are private.',
  sections: [
      { id: 'modules', title: 'Modules', body: 'Split into discrete apps: users, chats, messages, collaboration; each with repository/service boundaries.', order: 1 },
      { id: 'auth', title: 'Auth & Roles', body: 'JWT tokens + role gating; prepared for future granular permission claims.', order: 2 }
    ],
    gallery: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: 'domogreen-research-platform-flask',
    title: 'Domogreen Research Platform (Original)',
    tagline: 'Flask backend with role-based collaboration & chat',
    intro: 'Initial Flask + Firestore/then PostgreSQL backend enabling research chat, role workflows, and chatbot integration.',
    summary: 'Implemented role-based authorization, permissioned actions, chat creation & collaboration, and later migrated persistence to PostgreSQL for scale. Docker-ready deployment targeting GCP stateless infrastructure.',
    company: 'Domogreen',
    website: undefined,
    repository: null,
    domain: 'Backend',
    visibility: 'internal',
    access: 'proprietary',
    status: 'archived',
    start: '2024-09',
    end: '2025-01',
    role: 'Python Backend Engineer',
    stack: ['Flask', 'Python', 'PostgreSQL', 'Firebase Auth', 'Docker'],
    features: [
      'Role & permission actions',
      'Chat & collaboration',
      'Firestore → PostgreSQL migration',
      'Containerized deployment',
      'Chatbot integration hooks'
    ],
    sections: [
      { id: 'migration', title: 'Migration', body: 'Moved from Firestore to PostgreSQL to unlock relational querying, indexing, and cost predictability.', order: 1 },
      { id: 'roles', title: 'Roles', body: 'Implemented layered permission checks allowing future expansion without rewriting controllers.', order: 2 }
    ],
    gallery: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: 'aceitunaoil-wordpress-site',
    title: 'aceitunaoil.com – Multilingual Product Site',
    tagline: 'Custom one-page tri-language WordPress site',
    intro: 'A fully customized tri-language WordPress site showcasing products in English, Turkish, and Arabic.',
    summary: 'Delivered bespoke layout & content structure with multilingual support; collaborated with Kiwify Tech co-founders for branding alignment and international audience reach.',
    company: 'Client Project',
    website: 'https://aceitunaoil.com',
    repository: null,
    domain: 'WordPress',
    visibility: 'public',
    access: 'client-owned',
    status: 'live',
    start: '2024-07',
    end: '2024-07',
    role: 'WordPress Developer',
    stack: ['WordPress', 'Custom Theme', 'Multilingual'],
    features: [
      'Tri-language content',
      'Custom layout system',
      'Brand collaboration',
      'Responsive product sections'
    ],
    sections: [
      { id: 'localization', title: 'Localization', body: 'Structured content to ease translation layering without altering templates.', order: 1 }
    ],
    gallery: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: 'goldenhillsfood-wordpress-site',
    title: 'goldenhillsfood.com – Food Company Site',
    tagline: 'Bilingual corporate food brand presence',
    intro: 'One-page bilingual (English/Arabic) WordPress site for a food company.',
    summary: 'Focused on sleek product presentation, simplified maintenance, and multilingual support utilizing custom styling & content organization.',
    company: 'Client Project',
    website: 'https://goldenhillsfood.com',
    repository: null,
    domain: 'WordPress',
    visibility: 'public',
    access: 'client-owned',
    status: 'live',
    start: '2024-07',
    end: '2024-07',
    role: 'WordPress Developer',
    stack: ['WordPress', 'Custom CSS', 'Bilingual'],
    features: [
      'English/Arabic support',
      'Custom styling',
      'Product-focused layout'
    ],
    sections: [
      { id: 'design', title: 'Design', body: 'Crafted a clean layout emphasizing clarity over complexity for fast comprehension.', order: 1 }
    ],
    gallery: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: 'sezonco-hosting-support',
    title: 'sezonco.com.tr – Hosting & Support',
    tagline: 'Operational hosting, performance fixes & support',
    intro: 'Provided hosting management, bug fixes, and performance improvements for an existing client site.',
    summary: 'Delivered sustained operational support: environment stability, issue resolution, incremental performance enhancements.',
    company: 'Client Project',
    website: 'https://sezonco.com.tr',
    repository: null,
    domain: 'Ops',
    visibility: 'public',
    access: 'client-owned',
    status: 'live',
    start: '2024-08',
    role: 'Operations & Support Engineer',
    stack: ['Hosting', 'Performance', 'Bug Fixes'],
    features: [
      'Hosting management',
      'Issue remediation',
      'Stability improvements'
    ],
    sections: [
      { id: 'support', title: 'Support', body: 'Implemented a lightweight workflow for recurring fixes without heavy process overhead.', order: 1 }
    ],
    gallery: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: 'aanahtar-ecommerce-wordpress',
    title: 'aanahtar.com – eCommerce WordPress',
    tagline: 'Feature enhancements & maintenance for WooCommerce',
    intro: 'Contributed to development & maintenance of a full WordPress eCommerce site.',
    summary: 'Improved product listing flow, UI/UX refinements, and order management experience to enhance conversion and usability.',
    company: 'Client Project',
    website: 'https://aanahtar.com',
    repository: null,
    domain: 'WordPress',
    visibility: 'public',
    access: 'client-owned',
    status: 'live',
    start: '2024-06',
    role: 'WordPress Engineer',
    stack: ['WordPress', 'WooCommerce', 'UI Enhancements'],
    features: [
      'Product listing improvements',
      'Order management updates',
      'UX refinements'
    ],
    sections: [
      { id: 'improvements', title: 'Improvements', body: 'Focused on incremental improvements for customer journey and admin efficiency.', order: 1 }
    ],
    gallery: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: 'a4keys-migration-wholesale-plugin',
    title: 'a4keys.com – Migration & Wholesale Plugin',
    tagline: 'Full site migration + wholesale pricing plugin',
    intro: 'Migrated full site & database to new hosting while engineering a custom wholesale pricing management plugin.',
    summary: 'Ensured zero-downtime migration; delivered configurable wholesale pricing logic enabling efficient bulk operations for admins.',
    company: 'Client Project',
    website: 'https://a4keys.com',
    repository: null,
    domain: 'WordPress',
    visibility: 'public',
    access: 'client-owned',
    status: 'live',
    start: '2024-08',
    end: '2024-09',
    role: 'WordPress Engineer',
    stack: ['WordPress', 'Custom Plugin', 'Migration'],
    features: [
      'No-downtime migration',
      'Custom wholesale plugin',
      'Configurable pricing rules'
    ],
    sections: [
      { id: 'plugin', title: 'Plugin', body: 'Plugin abstracts pricing tiers & conditions for maintainability and future discount logic.', order: 1 }
    ],
    gallery: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: 'connect4-jquery-game',
    title: 'Connect 4 Game (jQuery)',
    tagline: 'Progressive iterations of an interactive browser game',
    intro: 'A multi-version Connect 4 browser game showcasing incremental improvements in UI, logic, and performance.',
    summary: 'Versioned evolution: basic DOM-based play → enhanced status/history → optimized 2D array logic. Demonstrates iterative refinement and front-end problem solving.',
    company: 'Personal Project',
    website: 'https://amarhany20.github.io/Jquery-Connect-4-Game/',
    repository: 'https://github.com/amarhany20/Jquery-Connect-4-Game',
    domain: 'Game',
    visibility: 'public',
    access: 'open-source',
    status: 'live',
    start: '2023-05',
    role: 'Front-end Developer',
    stack: ['HTML', 'CSS', 'JavaScript', 'jQuery', 'Bootstrap'],
    features: [
      'Iterative versioning',
      '2D array game state',
      'Responsive design',
      'Win detection optimization'
    ],
    sections: [
      { id: 'versions', title: 'Versions', body: 'Tracked improvements across v1, v2, v3 for clarity of capability evolution.', order: 1 }
    ],
    gallery: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: 'personal-website-static-v1',
    title: 'Personal Website (Static V1)',
    tagline: 'Foundational static portfolio & resume site',
    intro: 'Early static personal site built with HTML, CSS, JS, and Bootstrap organizing professional background into modular partials.',
    summary: 'Structured with partial includes (sections for education, projects, certificates, letters) enabling clean navigation and scalable content additions before transitioning to current Next.js platform.',
    company: 'Personal Project',
    website: 'https://github.com/amarhany20/Ammar-Personal-Website',
    repository: 'https://github.com/amarhany20/Ammar-Personal-Website',
    domain: 'Static',
    visibility: 'public',
    access: 'open-source',
    status: 'archived',
    start: '2022-11',
    end: '2023-04',
    role: 'Frontend Developer',
    stack: ['HTML', 'CSS', 'JavaScript', 'Bootstrap'],
    features: [
      'Section-based partials',
      'Responsive layout',
      'Early portfolio taxonomy'
    ],
    sections: [
      { id: 'evolution', title: 'Evolution', body: 'Served as the structural basis for future data separation & dynamic generation patterns.', order: 1 }
    ],
    gallery: [],
    createdAt: now,
    updatedAt: now,
  },
];

export function findProject(slug: string) {
  return portfolio.find(p => p.slug === slug) || null;
}
