// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/blogs" | "/admin/blogs/[slug]" | "/admin/blogs/new" | "/admin/certificates" | "/admin/certificates/[id]" | "/admin/certificates/new" | "/admin/contact" | "/admin/dashboard" | "/admin/education" | "/admin/education/[id]" | "/admin/education/new" | "/admin/experience" | "/admin/experience/[id]" | "/admin/experience/new" | "/admin/media" | "/admin/portfolio" | "/admin/portfolio/[slug]" | "/admin/portfolio/new" | "/admin/recommendations" | "/admin/recommendations/[id]" | "/admin/recommendations/new" | "/admin/services" | "/admin/services/[slug]" | "/admin/services/new" | "/admin/settings/setup" | "/admin/settings/theme" | "/admin/skills" | "/admin/skills/[slug]" | "/admin/skills/new" | "/blogs" | "/blogs/[slug]" | "/home" | "/login" | "/portfolio" | "/portfolio/[slug]" | "/services" | "/setup" | "/setup/[...slug]"
type AppRouteHandlerRoutes = "/api/setup" | "/api/setup/database" | "/api/setup/test-database" | "/api/v1/auth/login" | "/api/v1/auth/logout" | "/api/v1/blogs" | "/api/v1/blogs/[slug]" | "/api/v1/certificates" | "/api/v1/certificates/[id]" | "/api/v1/contact" | "/api/v1/contact/[id]" | "/api/v1/education" | "/api/v1/education/[id]" | "/api/v1/example" | "/api/v1/experience" | "/api/v1/experience/[id]" | "/api/v1/media" | "/api/v1/media/[id]" | "/api/v1/portfolio" | "/api/v1/portfolio/[slug]" | "/api/v1/portfolio/reorder" | "/api/v1/recommendations" | "/api/v1/recommendations/[id]" | "/api/v1/services" | "/api/v1/services/[slug]" | "/api/v1/services/reorder" | "/api/v1/skills" | "/api/v1/skills/[slug]" | "/api/v1/themes" | "/api/v1/themes/apply"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/blogs": {}
  "/admin/blogs/[slug]": { "slug": string; }
  "/admin/blogs/new": {}
  "/admin/certificates": {}
  "/admin/certificates/[id]": { "id": string; }
  "/admin/certificates/new": {}
  "/admin/contact": {}
  "/admin/dashboard": {}
  "/admin/education": {}
  "/admin/education/[id]": { "id": string; }
  "/admin/education/new": {}
  "/admin/experience": {}
  "/admin/experience/[id]": { "id": string; }
  "/admin/experience/new": {}
  "/admin/media": {}
  "/admin/portfolio": {}
  "/admin/portfolio/[slug]": { "slug": string; }
  "/admin/portfolio/new": {}
  "/admin/recommendations": {}
  "/admin/recommendations/[id]": { "id": string; }
  "/admin/recommendations/new": {}
  "/admin/services": {}
  "/admin/services/[slug]": { "slug": string; }
  "/admin/services/new": {}
  "/admin/settings/setup": {}
  "/admin/settings/theme": {}
  "/admin/skills": {}
  "/admin/skills/[slug]": { "slug": string; }
  "/admin/skills/new": {}
  "/api/setup": {}
  "/api/setup/database": {}
  "/api/setup/test-database": {}
  "/api/v1/auth/login": {}
  "/api/v1/auth/logout": {}
  "/api/v1/blogs": {}
  "/api/v1/blogs/[slug]": { "slug": string; }
  "/api/v1/certificates": {}
  "/api/v1/certificates/[id]": { "id": string; }
  "/api/v1/contact": {}
  "/api/v1/contact/[id]": { "id": string; }
  "/api/v1/education": {}
  "/api/v1/education/[id]": { "id": string; }
  "/api/v1/example": {}
  "/api/v1/experience": {}
  "/api/v1/experience/[id]": { "id": string; }
  "/api/v1/media": {}
  "/api/v1/media/[id]": { "id": string; }
  "/api/v1/portfolio": {}
  "/api/v1/portfolio/[slug]": { "slug": string; }
  "/api/v1/portfolio/reorder": {}
  "/api/v1/recommendations": {}
  "/api/v1/recommendations/[id]": { "id": string; }
  "/api/v1/services": {}
  "/api/v1/services/[slug]": { "slug": string; }
  "/api/v1/services/reorder": {}
  "/api/v1/skills": {}
  "/api/v1/skills/[slug]": { "slug": string; }
  "/api/v1/themes": {}
  "/api/v1/themes/apply": {}
  "/blogs": {}
  "/blogs/[slug]": { "slug": string; }
  "/home": {}
  "/login": {}
  "/portfolio": {}
  "/portfolio/[slug]": { "slug": string; }
  "/services": {}
  "/setup": {}
  "/setup/[...slug]": { "slug": string[]; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
