// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/(public)/setup/[...slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/setup/[...slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/(public)/setup/[...slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(public)/setup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/setup">> = Specific
  const handler = {} as typeof import("../../../src/app/(public)/setup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/blogs/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/blogs/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/blogs/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/blogs/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/blogs/new">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/blogs/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/blogs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/blogs">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/blogs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/certificates/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/certificates/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/certificates/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/certificates/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/certificates/new">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/certificates/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/certificates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/certificates">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/certificates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/contact">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/education/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/education/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/education/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/education/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/education/new">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/education/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/education/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/education">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/education/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/experience/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/experience/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/experience/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/experience/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/experience/new">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/experience/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/experience/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/experience">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/experience/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/media/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/media">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/media/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/portfolio/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/portfolio/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/portfolio/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/portfolio/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/portfolio/new">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/portfolio/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/portfolio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/portfolio">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/portfolio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/recommendations/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/recommendations/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/recommendations/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/recommendations/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/recommendations/new">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/recommendations/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/recommendations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/recommendations">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/recommendations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/services/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/services/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/services/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/services/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/services/new">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/services/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/services">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/settings/setup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings/setup">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/settings/setup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/settings/theme/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings/theme">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/settings/theme/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/skills/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/skills/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/skills/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/skills/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/skills/new">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/skills/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/skills/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/skills">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/skills/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/blogs/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blogs/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/blogs/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/blogs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blogs">> = Specific
  const handler = {} as typeof import("../../../src/app/blogs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/home/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/home">> = Specific
  const handler = {} as typeof import("../../../src/app/home/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/portfolio/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portfolio/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/portfolio/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/portfolio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portfolio">> = Specific
  const handler = {} as typeof import("../../../src/app/portfolio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services">> = Specific
  const handler = {} as typeof import("../../../src/app/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/auth/login">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/auth/logout">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/blogs/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/blogs/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/blogs/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/blogs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/blogs">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/blogs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/certificates/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/certificates/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/certificates/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/certificates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/certificates">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/certificates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/contact/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/contact/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/contact/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/contact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/contact">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/contact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/education/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/education/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/education/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/education/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/education">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/education/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/example/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/example">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/example/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/experience/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/experience/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/experience/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/experience/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/experience">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/experience/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/media/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/media/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/media/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/media/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/media">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/media/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/portfolio/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/portfolio/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/portfolio/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/portfolio/reorder/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/portfolio/reorder">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/portfolio/reorder/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/portfolio/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/portfolio">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/portfolio/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/recommendations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/recommendations/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/recommendations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/recommendations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/recommendations">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/recommendations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/services/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/services/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/services/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/services/reorder/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/services/reorder">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/services/reorder/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/services/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/services">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/services/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/skills/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/skills/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/skills/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/skills/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/skills">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/skills/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/themes/apply/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/themes/apply">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/themes/apply/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/themes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/themes">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/themes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
